-- VitalGo Complete Countries Data
-- Adding remaining countries to reach full global coverage

BEGIN;

-- Insert remaining countries (sorted by region)
INSERT INTO countries (name, code, flag_emoji, phone_code, is_active) VALUES

-- Resto del Caribe
('Antigua y Barbuda', 'AG', '🇦🇬', '+1-268', true),
('Aruba', 'AW', '🇦🇼', '+297', true),
('Curazao', 'CW', '🇨🇼', '+599', true),
('Dominica', 'DM', '🇩🇲', '+1-767', true),
('Granada', 'GD', '🇬🇩', '+1-473', true),
('Guadalupe', 'GP', '🇬🇵', '+590', true),
('Martinica', 'MQ', '🇲🇶', '+596', true),
('San Cristóbal y Nieves', 'KN', '🇰🇳', '+1-869', true),
('Santa Lucía', 'LC', '🇱🇨', '+1-758', true),
('San Vicente y las Granadinas', 'VC', '🇻🇨', '+1-784', true),

-- Europa (resto)
('Albania', 'AL', '🇦🇱', '+355', true),
('Andorra', 'AD', '🇦🇩', '+376', true),
('Armenia', 'AM', '🇦🇲', '+374', true),
('Austria', 'AT', '🇦🇹', '+43', true),
('Azerbaiyán', 'AZ', '🇦🇿', '+994', true),
('Bielorrusia', 'BY', '🇧🇾', '+375', true),
('Bosnia y Herzegovina', 'BA', '🇧🇦', '+387', true),
('Bulgaria', 'BG', '🇧🇬', '+359', true),
('Croacia', 'HR', '🇭🇷', '+385', true),
('Chipre', 'CY', '🇨🇾', '+357', true),
('República Checa', 'CZ', '🇨🇿', '+420', true),
('Estonia', 'EE', '🇪🇪', '+372', true),
('Finlandia', 'FI', '🇫🇮', '+358', true),
('Georgia', 'GE', '🇬🇪', '+995', true),
('Grecia', 'GR', '🇬🇷', '+30', true),
('Hungría', 'HU', '🇭🇺', '+36', true),
('Islandia', 'IS', '🇮🇸', '+354', true),
('Irlanda', 'IE', '🇮🇪', '+353', true),
('Kazajistán', 'KZ', '🇰🇿', '+7', true),
('Kosovo', 'XK', '🇽🇰', '+383', true),
('Letonia', 'LV', '🇱🇻', '+371', true),
('Liechtenstein', 'LI', '🇱🇮', '+423', true),
('Lituania', 'LT', '🇱🇹', '+370', true),
('Luxemburgo', 'LU', '🇱🇺', '+352', true),
('Macedonia del Norte', 'MK', '🇲🇰', '+389', true),
('Malta', 'MT', '🇲🇹', '+356', true),
('Moldavia', 'MD', '🇲🇩', '+373', true),
('Mónaco', 'MC', '🇲🇨', '+377', true),
('Montenegro', 'ME', '🇲🇪', '+382', true),
('Rumania', 'RO', '🇷🇴', '+40', true),
('San Marino', 'SM', '🇸🇲', '+378', true),
('Serbia', 'RS', '🇷🇸', '+381', true),
('Eslovaquia', 'SK', '🇸🇰', '+421', true),
('Eslovenia', 'SI', '🇸🇮', '+386', true),
('Ucrania', 'UA', '🇺🇦', '+380', true),
('Ciudad del Vaticano', 'VA', '🇻🇦', '+39', true),

-- Asia (resto)
('Afganistán', 'AF', '🇦🇫', '+93', true),
('Baréin', 'BH', '🇧🇭', '+973', true),
('Bangladés', 'BD', '🇧🇩', '+880', true),
('Bután', 'BT', '🇧🇹', '+975', true),
('Brunéi', 'BN', '🇧🇳', '+673', true),
('Camboya', 'KH', '🇰🇭', '+855', true),
('Corea del Norte', 'KP', '🇰🇵', '+850', true),
('Hong Kong', 'HK', '🇭🇰', '+852', true),
('Irak', 'IQ', '🇮🇶', '+964', true),
('Irán', 'IR', '🇮🇷', '+98', true),
('Jordania', 'JO', '🇯🇴', '+962', true),
('Kuwait', 'KW', '🇰🇼', '+965', true),
('Kirguistán', 'KG', '🇰🇬', '+996', true),
('Laos', 'LA', '🇱🇦', '+856', true),
('Líbano', 'LB', '🇱🇧', '+961', true),
('Macao', 'MO', '🇲🇴', '+853', true),
('Maldivas', 'MV', '🇲🇻', '+960', true),
('Mongolia', 'MN', '🇲🇳', '+976', true),
('Myanmar', 'MM', '🇲🇲', '+95', true),
('Nepal', 'NP', '🇳🇵', '+977', true),
('Omán', 'OM', '🇴🇲', '+968', true),
('Pakistán', 'PK', '🇵🇰', '+92', true),
('Palestina', 'PS', '🇵🇸', '+970', true),
('Catar', 'QA', '🇶🇦', '+974', true),
('Siria', 'SY', '🇸🇾', '+963', true),
('Taiwán', 'TW', '🇹🇼', '+886', true),
('Tayikistán', 'TJ', '🇹🇯', '+992', true),
('Timor Oriental', 'TL', '🇹🇱', '+670', true),
('Turkmenistán', 'TM', '🇹🇲', '+993', true),
('Uzbekistán', 'UZ', '🇺🇿', '+998', true),
('Yemen', 'YE', '🇾🇪', '+967', true),

-- África (resto)
('Angola', 'AO', '🇦🇴', '+244', true),
('Benín', 'BJ', '🇧🇯', '+229', true),
('Botsuana', 'BW', '🇧🇼', '+267', true),
('Burkina Faso', 'BF', '🇧🇫', '+226', true),
('Burundi', 'BI', '🇧🇮', '+257', true),
('Cabo Verde', 'CV', '🇨🇻', '+238', true),
('Camerún', 'CM', '🇨🇲', '+237', true),
('Chad', 'TD', '🇹🇩', '+235', true),
('Comoras', 'KM', '🇰🇲', '+269', true),
('Congo', 'CG', '🇨🇬', '+242', true),
('República Democrática del Congo', 'CD', '🇨🇩', '+243', true),
('Costa de Marfil', 'CI', '🇨🇮', '+225', true),
('Yibuti', 'DJ', '🇩🇯', '+253', true),
('Guinea Ecuatorial', 'GQ', '🇬🇶', '+240', true),
('Eritrea', 'ER', '🇪🇷', '+291', true),
('Etiopía', 'ET', '🇪🇹', '+251', true),
('Gabón', 'GA', '🇬🇦', '+241', true),
('Gambia', 'GM', '🇬🇲', '+220', true),
('Guinea', 'GN', '🇬🇳', '+224', true),
('Guinea-Bisáu', 'GW', '🇬🇼', '+245', true),
('Lesoto', 'LS', '🇱🇸', '+266', true),
('Liberia', 'LR', '🇱🇷', '+231', true),
('Libia', 'LY', '🇱🇾', '+218', true),
('Madagascar', 'MG', '🇲🇬', '+261', true),
('Malaui', 'MW', '🇲🇼', '+265', true),
('Malí', 'ML', '🇲🇱', '+223', true),
('Mauritania', 'MR', '🇲🇷', '+222', true),
('Mauricio', 'MU', '🇲🇺', '+230', true),
('Mozambique', 'MZ', '🇲🇿', '+258', true),
('Namibia', 'NA', '🇳🇦', '+264', true),
('Níger', 'NE', '🇳🇪', '+227', true),
('Ruanda', 'RW', '🇷🇼', '+250', true),
('Santo Tomé y Príncipe', 'ST', '🇸🇹', '+239', true),
('Senegal', 'SN', '🇸🇳', '+221', true),
('Seychelles', 'SC', '🇸🇨', '+248', true),
('Sierra Leona', 'SL', '🇸🇱', '+232', true),
('Somalia', 'SO', '🇸🇴', '+252', true),
('Sudán del Sur', 'SS', '🇸🇸', '+211', true),
('Sudán', 'SD', '🇸🇩', '+249', true),
('Suazilandia', 'SZ', '🇸🇿', '+268', true),
('Tanzania', 'TZ', '🇹🇿', '+255', true),
('Togo', 'TG', '🇹🇬', '+228', true),
('Túnez', 'TN', '🇹🇳', '+216', true),
('Uganda', 'UG', '🇺🇬', '+256', true),
('Zambia', 'ZM', '🇿🇲', '+260', true),
('Zimbabue', 'ZW', '🇿🇼', '+263', true),

-- Oceanía (resto)
('Fiji', 'FJ', '🇫🇯', '+679', true),
('Kiribati', 'KI', '🇰🇮', '+686', true),
('Islas Marshall', 'MH', '🇲🇭', '+692', true),
('Micronesia', 'FM', '🇫🇲', '+691', true),
('Nauru', 'NR', '🇳🇷', '+674', true),
('Palaos', 'PW', '🇵🇼', '+680', true),
('Papúa Nueva Guinea', 'PG', '🇵🇬', '+675', true),
('Samoa', 'WS', '🇼🇸', '+685', true),
('Islas Salomón', 'SB', '🇸🇧', '+677', true),
('Tonga', 'TO', '🇹🇴', '+676', true),
('Tuvalu', 'TV', '🇹🇻', '+688', true),
('Vanuatu', 'VU', '🇻🇺', '+678', true),

-- Territorios importantes
('Groenlandia', 'GL', '🇬🇱', '+299', true),
('Islas Feroe', 'FO', '🇫🇴', '+298', true),
('Nueva Caledonia', 'NC', '🇳🇨', '+687', true),
('Polinesia Francesa', 'PF', '🇵🇫', '+689', true),
('Reunión', 'RE', '🇷🇪', '+262', true),
('Mayotte', 'YT', '🇾🇹', '+262', true),
('Islas Vírgenes de EE.UU.', 'VI', '🇻🇮', '+1-340', true),
('Guam', 'GU', '🇬🇺', '+1-671', true),
('Samoa Americana', 'AS', '🇦🇸', '+1-684', true),
('Islas Caimán', 'KY', '🇰🇾', '+1-345', true),
('Bermudas', 'BM', '🇧🇲', '+1-441', true),
('Gibraltar', 'GI', '🇬🇮', '+350', true),
('Isla de Man', 'IM', '🇮🇲', '+44', true),
('Jersey', 'JE', '🇯🇪', '+44', true),
('Guernsey', 'GG', '🇬🇬', '+44', true)

ON CONFLICT (code) DO NOTHING;

COMMIT;

-- Verify total countries
SELECT COUNT(*) as total_countries FROM countries;
SELECT COUNT(*) as active_countries FROM countries WHERE is_active = true;
